@startuml
start
:Пользователь добавляет новую карточку;
:Пользователь вводит текущий баланс карточки;
if (Баланс введен?) then (Да)
  :Система выполняет валидацию данных;
  if (Данные корректны) then (Да)
    :Система сохраняет данные;
  else (Нет)
    :Система отображает ошибку;
  endif
else (Нет)
  :Система отображает ошибку;
endif
stop
@enduml