@startuml
start
:Пользователь вносит информацию о расходах;
:Пользователь вводит сумму расхода;
if (Сумма введена?) then (Да)
  :Пользователь выбирает категорию расхода;
  if (Категория выбрана?) then (Да)
    :Пользователь вводит дату расхода;
    if (Дата введена?) then (Да)
      :Система выполняет валидацию данных;
      if (Данные корректны) then (Да)
        :Система сохраняет данные;
      else (Нет)
        :Система отображает ошибку;
      endif
    else (Нет)
      :Система отображает ошибку;
    endif
  else (Нет)
    :Система отображает ошибку;
  endif
else (Нет)
  :Система отображает ошибку;
endif
stop
@enduml