@startuml
start
:Пользователь вносит информацию о заработках;
:Пользователь вводит сумму заработка;
if (Сумма введена?) then (Да)
  :Система выполняет валидацию данных;
  if (Данные корректны) then (Да)
    :Система сохраняет данные;
  else (Нет)
    :Система отображает ошибку;
  endif
else (Нет)
  :Система отображает ошибку;
endif
stop
@enduml