@startuml
start
:Генерация отчетов;
:Пользователь выбирает период для отчета;
if (Период выбран?) then (Да)
  :Система выполняет генерацию отчетов для выбранного периода;
  if (Отчеты сгенерированы?) then (Да)
    :Отображение статистики;
  else (Нет)
    :Система предупреждает об ошибке;
  endif
else (Нет)
  :Система предупреждает об ошибке;
endif
stop
@enduml